name: Security audit
on:
  pull_request:
  workflow_dispatch:
  #schedule:
  #  - cron: '1 40 * * *'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: 'stable'
          check-latest: true
